"""Se actualiza tabla de vehiculos

Revision ID: f240f833d4e0
Revises: 740b057df44f
Create Date: 2024-09-30 20:24:48.738624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f240f833d4e0'
down_revision: Union[str, None] = '740b057df44f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el tipo ENUM primero
    op.execute("CREATE TYPE vincodesourceenum AS ENUM ('qr', 'bar_code')")

    op.add_column('vehicles', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('vehicles', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('vehicles', sa.Column('is_urgency', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('vehicles', sa.Column('plate', sa.String(length=6), nullable=True))
    op.add_column('vehicles', sa.Column('vin_code_source', sa.Enum('qr', 'bar_code', name='vincodesourceenum'), nullable=False))
    op.add_column('vehicles', sa.Column('is_damaged', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('vehicles', sa.Column('is_only_wash', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('vehicles', sa.Column('status', sa.Integer(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'created_at')
    op.drop_column('vehicles', 'updated_at')
    op.drop_column('vehicles', 'is_urgency')
    op.drop_column('vehicles', 'plate')
    op.drop_column('vehicles', 'vin_code_source')
    op.drop_column('vehicles', 'is_damaged')
    op.drop_column('vehicles', 'is_only_wash')
    op.drop_column('vehicles', 'status')
    
    # Eliminar el tipo ENUM creado
    op.execute("DROP TYPE vincodesourceenum")