"""table names remaned 2

Revision ID: f43e80fdb5f8
Revises: 6975310891a4
Create Date: 2024-10-01 16:39:37.143745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f43e80fdb5f8'
down_revision: Union[str, None] = '6975310891a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brand_id'), 'brand', ['id'], unique=False)
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.create_index(op.f('ix_model_id'), 'model', ['id'], unique=False)
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    op.create_index(op.f('ix_vehicle_type_id'), 'vehicle_type', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_type_type_name'), 'vehicle_type', ['type_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_type_type_name'), table_name='vehicle_type')
    op.drop_index(op.f('ix_vehicle_type_id'), table_name='vehicle_type')
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_index(op.f('ix_model_id'), table_name='model')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index(op.f('ix_brand_id'), table_name='brand')
    # ### end Alembic commands ###
